import { Injectable } from '@nestjs/common';
import { ENV_KEYS, EnvService } from 'src/infrastructure/framework/env.service';

@Injectable()
export class VehicleUtil {
  private readonly _urlBrands: string;
  private readonly _filenamesOnS3WithOutDefaultImage: ReadonlyArray<string> = [
    'rodolinea',
    'triel-ht',
    'metalesp',
    'itapemirim',
    'kronorte',
    'hyosung',
    'free-hobby',
    'caterpillar',
    'ciber',
    'aima',
    'valtra',
    'oldsmobile',
    'new-holland',
    'mercury',
    'man',
    'loncin',
    'lg',
    'krone',
    'karmann-ghia',
    'kasinski',
    'jonway',
    'jinbei',
    'infiniti',
    'grove',
    'great-wall',
    'foton',
    'dayang',
    'dfm',
    'case',
    'byd',
    'bramont',
    'biasi',
    'bashan',
    'aston-martin',
    'aprilia',
    'zongshen',
    'zoomlion',
    'yingang',
    'turiscar',
    'terex',
    'truckvan',
    'tadano-faun',
    'ssangyong',
    'sinotruk',
    'smarda',
    'sergomel',
    'sany',
    'rolls-royce',
    'rodovale',
    'rodofort',
    'rhodoss',
    'puma',
    'plymouth',
    'packard',
    'pastre',
    'librelato',
    'lambretta',
    'lada',
    'ktm',
    'jmc',
    'johndeere',
    'jac',
    'harley-davidson',
    'hafei',
    'guerra',
    'gurgel',
    'gmc',
    'gelly',
    'engesa',
    'facchini',
    'chana',
    'daf',
    'caoa-chery',
    'cadillac',
    'caloi',
    'busscar',
    'buick',
    'alfa-romeo',
    'buell',
    'acura',
    'xcmg',
    'triumph',
    'sundown',
    'shineray',
    'royal-enfield',
    'scania',
    'recrusul',
    'randon',
    'pontiac',
    'ram',
    'noma',
    'mvk',
    'monark',
    'mv-agusta',
    'massey-ferguson',
    'marcopolo',
    'mahindra',
    'lincoln',
    'lobini',
    'liebherr',
    'abarth',
    'agrale',
    'audi',
    'avelloz',
    'bentley',
    'bmw',
    'brp',
    'bugatti',
    'chery',
    'chevrolet',
    'gm',
    'chrysler',
    'citroen',
    'dacia',
    'daewoo',
    'dafra',
    'dodge',
    'ducati',
    'effa',
    'ferrari',
    'fiat',
    'ford',
    'honda',
    'hummer',
    'husqvarna',
    'hyundai',
    'iveco',
    'jaguar',
    'jeep',
    'jtz',
    'kawasaki',
    'kia',
    'lamborghini',
    'lancia',
    'land-rover',
    'lexus',
    'lifan',
    'lotus',
    'maserati',
    'mazda',
    'mclaren',
    'mercedes-benz',
    'mg',
    'mini',
    'mitsubishi',
    'morgan',
    'nissan',
    'opel',
    'peugeot',
    'piaggio',
    'porsche',
    'renault',
    'saab',
    'seat',
    'smart',
    'subaru',
    'suzuki',
    'tata',
    'tesla',
    'toyota',
    'troller',
    'vespa',
    'volkswagen',
    'volvo',
    'yamaha',
  ];

  constructor(private readonly _envService: EnvService) {
    this._urlBrands = `${_envService.get(ENV_KEYS.AMAZON_S3_URL)}/brands`;
  }

  getBrandImgSrc(brandName: string): string {
    const brandString: string = this._normalizeBrandName(brandName);

    if (!this._filenamesOnS3WithOutDefaultImage.includes(brandString)) {
      return `${this._urlBrands}/default.webp`;
    }

    return `${this._urlBrands}/${brandString}.webp`;
  }

  private _normalizeBrandName(brandName: string): string {
    if (!brandName) return null;
    return brandName?.replace('I/', '')?.replace(' ', '-')?.toLowerCase();
  }
}
