import { Injectable } from '@nestjs/common';
import {
  BrandImage,
  ModelImage,
  VehicleImageService,
} from 'src/domain/_layer/infrastructure/service/vehicle-image.service';

type StaticBrandImage = { readonly filename: string; readonly name: string };

@Injectable()
export class StaticVehicleImageService implements VehicleImageService {
  static brandImages: ReadonlyArray<readonly [string, StaticBrandImage]> = [
    ['abarth', { filename: 'abarth', name: 'Abarth' }],
    ['acura', { filename: 'acura', name: 'Acura' }],
    ['adly', { filename: 'adly', name: 'ADLY' }],
    ['agrale', { filename: 'agrale', name: 'Agrale' }],
    ['alfa', { filename: 'alfa-romeo', name: 'Alfa-Romeo' }],
    ['am gen', { filename: 'am-gen', name: 'AM Gen' }],
    ['amazonas', { filename: 'amazonas', name: 'AMAZONAS' }],
    ['aprilia', { filename: 'aprilia', name: 'APRILIA' }],
    ['asia motors', { filename: 'asia-motors', name: 'Asia Motors' }],
    ['aston', { filename: 'aston-martin', name: 'Aston-Martin' }],
    ['atala', { filename: 'atala', name: 'ATALA' }],
    ['audi', { filename: 'audi', name: 'Audi' }],
    ['avelloz', { filename: 'avelloz', name: 'Avelloz' }],
    ['baby', { filename: 'default', name: 'Baby' }],
    ['bajaj', { filename: 'bajaj', name: 'BAJAJ' }],
    ['bee', { filename: 'bee', name: 'BEE' }],
    ['benelli', { filename: 'benelli', name: 'Benelli' }],
    ['bentley', { filename: 'bentley', name: 'Bentley' }],
    ['bepobus', { filename: 'bepobus', name: 'BEPOBUS' }],
    ['beta', { filename: 'beta', name: 'BETA' }],
    ['bimota', { filename: 'bimota', name: 'BIMOTA' }],
    ['bmw', { filename: 'bmw', name: 'BMW' }],
    ['brandy', { filename: 'default', name: 'BRANDY' }],
    ['brava', { filename: 'default', name: 'BRAVA' }],
    ['brm', { filename: 'brm', name: 'BRM' }],
    ['brp', { filename: 'brp', name: 'BRP' }],
    ['buell', { filename: 'buell', name: 'Buell' }],
    ['bueno', { filename: 'default', name: 'BUENO' }],
    ['bugatti', { filename: 'bugatti', name: 'Bugatti' }],
    ['buggy', { filename: 'default', name: 'Buggy' }],
    ['bugre', { filename: 'default', name: 'Bugre' }],
    ['bull', { filename: 'bull', name: 'BULL' }],
    ['bycristo', { filename: 'default', name: 'byCristo' }],
    ['byd', { filename: 'byd', name: 'BYD' }],
    ['cab motors', { filename: 'default', name: 'CAB Motors' }],
    ['cadillac', { filename: 'cadillac', name: 'Cadillac' }],
    ['cagiva', { filename: 'cagiva', name: 'CAGIVA' }],
    ['caloi', { filename: 'caloi', name: 'CALOI' }],
    ['caoa chery', { filename: 'caoa-chery', name: 'Caoa Chery' }],
    ['cbt jipe', { filename: 'default', name: 'CBT Jipe' }],
    ['chana', { filename: 'chana', name: 'Chana' }],
    ['changan', { filename: 'changan', name: 'CHANGAN' }],
    ['chery', { filename: 'chery', name: 'Chery' }],
    ['chev', { filename: 'chevrolet', name: 'Chevrolet' }],
    ['chrysler', { filename: 'chrysler', name: 'Chrysler' }],
    ['ciccobus', { filename: 'default', name: 'CICCOBUS' }],
    ['citro', { filename: 'citroen', name: 'Citroën' }],
    ['cross lander', { filename: 'cross-lander', name: 'Cross Lander' }],
    ['d2d motors', { filename: 'd2d-motors', name: 'D2D Motors' }],
    ['d2d', { filename: 'd2d-motors', name: 'D2D' }],
    ['dacia', { filename: 'dacia', name: 'Dacia' }],
    ['daelim', { filename: 'daelim', name: 'DAELIM' }],
    ['daewoo', { filename: 'daewoo', name: 'Daewoo' }],
    ['daf', { filename: 'daf', name: 'DAF' }],
    ['dafra', { filename: 'dafra', name: 'Dafra' }],
    ['daihatsu', { filename: 'daihatsu', name: 'Daihatsu' }],
    ['dayang', { filename: 'dayang', name: 'DAYANG' }],
    ['dayun', { filename: 'dayun', name: 'DAYUN' }],
    ['derbi', { filename: 'derbi', name: 'DERBI' }],
    ['dfsk', { filename: 'dfsk', name: 'DFSK' }],
    ['dodge', { filename: 'dodge', name: 'Dodge' }],
    ['ducati', { filename: 'ducati', name: 'Ducati' }],
    ['effa', { filename: 'effa', name: 'Effa' }],
    ['emme', { filename: 'default', name: 'EMME' }],
    ['engesa', { filename: 'engesa', name: 'Engesa' }],
    ['envemo', { filename: 'default', name: 'Envemo' }],
    ['ferrari', { filename: 'ferrari', name: 'Ferrari' }],
    ['fever', { filename: 'default', name: 'FEVER' }],
    ['fiat', { filename: 'fiat', name: 'Fiat' }],
    ['fibravan', { filename: 'default', name: 'Fibravan' }],
    ['ford', { filename: 'ford', name: 'Ford' }],
    ['foton', { filename: 'foton', name: 'FOTON' }],
    ['fox', { filename: 'default', name: 'FOX' }],
    ['fusco motosegura', { filename: 'fusco-motosegura', name: 'FUSCO MOTOSEGURA' }],
    ['fyber', { filename: 'default', name: 'Fyber' }],
    ['fym', { filename: 'default', name: 'FYM' }],
    ['garinni', { filename: 'default', name: 'GARINNI' }],
    ['gas gas', { filename: 'gas-gas', name: 'GAS GAS' }],
    ['geely', { filename: 'gelly', name: 'Geely' }],
    ['gm', { filename: 'chevrolet', name: 'Chevrolet' }],
    ['great wall', { filename: 'great-wall', name: 'GREAT WALL' }],
    ['green', { filename: 'default', name: 'GREEN' }],
    ['gurgel', { filename: 'gurgel', name: 'Gurgel' }],
    ['gwm', { filename: 'default', name: 'GWM' }],
    ['h.davidson', { filename: 'harley-davidson', name: 'Harley-Davidson' }],
    ['hafei', { filename: 'hafei', name: 'Hafei' }],
    ['haobao', { filename: 'default', name: 'HAOBAO' }],
    ['haojue', { filename: 'haojue', name: 'HAOJUE' }],
    ['harley', { filename: 'harley-davidson', name: 'Harley-Davidson' }],
    ['hartford', { filename: 'default', name: 'HARTFORD' }],
    ['hero', { filename: 'hero', name: 'HERO' }],
    ['hitech electric', { filename: 'hitech-electric', name: 'HITECH ELECTRIC' }],
    ['hitech eletric', { filename: 'hitech-electric', name: 'HITECH ELECTRIC' }],
    ['honda', { filename: 'honda', name: 'Honda' }],
    ['hummer', { filename: 'hummer', name: 'Hummer' }],
    ['husaberg', { filename: 'husaberg', name: 'HUSABERG' }],
    ['husqvarna', { filename: 'husqvarna', name: 'Husqvarna' }],
    ['hyundai', { filename: 'hyundai', name: 'Hyundai' }],
    ['indian', { filename: 'indian', name: 'INDIAN' }],
    ['iros', { filename: 'iros', name: 'IROS' }],
    ['isuzu', { filename: 'isuzu', name: 'Isuzu' }],
    ['iveco', { filename: 'iveco', name: 'Iveco' }],
    ['jac', { filename: 'jac', name: 'JAC' }],
    ['jaguar', { filename: 'jaguar', name: 'Jaguar' }],
    ['jeep', { filename: 'jeep', name: 'Jeep' }],
    ['jiapeng volcano', { filename: 'default', name: 'JIAPENG VOLCANO' }],
    ['jinbei', { filename: 'jinbei', name: 'JINBEI' }],
    ['johnnypag', { filename: 'default', name: 'JOHNNYPAG' }],
    ['jonny', { filename: 'default', name: 'JONNY' }],
    ['jpx', { filename: 'jpx', name: 'JPX' }],
    ['jtz', { filename: 'jtz', name: 'JTZ' }],
    ['kahena', { filename: 'default', name: 'KAHENA' }],
    ['kasinski', { filename: 'kasinski', name: 'Kasinski' }],
    ['kawasaki', { filename: 'kawasaki', name: 'Kawasaki' }],
    ['kia', { filename: 'kia', name: 'KIA' }],
    ['kimco', { filename: 'default', name: 'KIMCO' }],
    ['ktm', { filename: 'ktm', name: 'KTM' }],
    ['kymco', { filename: 'kymco', name: 'KYMCO' }],
    ['lada', { filename: 'lada', name: 'Lada' }],
    ['lamborghini', { filename: 'lamborghini', name: 'Lamborghini' }],
    ['lancia', { filename: 'lancia', name: 'Lancia' }],
    ['land', { filename: 'land-rover', name: 'Land-Rover' }],
    ['lavrale', { filename: 'default', name: 'LAVRALE' }],
    ['lerivo', { filename: 'default', name: 'LERIVO' }],
    ['lexus', { filename: 'lexus', name: 'Lexus' }],
    ['lifan', { filename: 'lifan', name: 'Lifan' }],
    ['lobini', { filename: 'lobini', name: 'Lobini' }],
    ['lon-v', { filename: 'default', name: 'Lon-V' }],
    ['lotus', { filename: 'lotus', name: 'Lotus' }],
    ['lr', { filename: 'land-rover', name: 'Land-Rover' }],
    ['m.benz', { filename: 'mercedes-benz', name: 'Mercedes-Benz' }],
    ['magrão triciclos', { filename: 'default', name: 'MAGRÃO TRICICLOS' }],
    ['mahindra', { filename: 'mahindra', name: 'Mahindra' }],
    ['malaguti', { filename: 'malaguti', name: 'Malaguti' }],
    ['man', { filename: 'man', name: 'MAN' }],
    ['marcopolo', { filename: 'marcopolo', name: 'MARCOPOLO' }],
    ['mascarello', { filename: 'mascarello', name: 'MASCARELLO' }],
    ['maserati', { filename: 'maserati', name: 'Maserati' }],
    ['matra', { filename: 'default', name: 'Matra' }],
    ['maxibus', { filename: 'maxibus', name: 'MAXIBUS' }],
    ['mazda', { filename: 'mazda', name: 'Mazda' }],
    ['mclaren', { filename: 'mclaren', name: 'McLaren' }],
    ['mercedes', { filename: 'mercedes-benz', name: 'Mercedes-Benz' }],
    ['mercury', { filename: 'mercury', name: 'Mercury' }],
    ['mg', { filename: 'mg', name: 'MG' }],
    ['mini', { filename: 'mini', name: 'Mini' }],
    ['mitsubishi', { filename: 'mitsubishi', name: 'Mitsubishi' }],
    ['miura', { filename: 'default', name: 'Miura' }],
    ['miza', { filename: 'miza', name: 'MIZA' }],
    ['mmc', { filename: 'mitsubishi', name: 'Mitsubishi' }],
    ['morgan', { filename: 'morgan', name: 'Morgan' }],
    ['moto guzzi', { filename: 'moto-guzzi', name: 'MOTO GUZZI' }],
    ['motocar', { filename: 'default', name: 'MOTOCAR' }],
    ['motorino', { filename: 'default', name: 'MOTORINO' }],
    ['mrx', { filename: 'default', name: 'MRX' }],
    ['mv agusta', { filename: 'mv-agusta', name: 'MV Agusta' }],
    ['mvk', { filename: 'default', name: 'MVK' }],
    ['navistar', { filename: 'navistar', name: 'NAVISTAR' }],
    ['neobus', { filename: 'neobus', name: 'NEOBUS' }],
    ['nissan', { filename: 'nissan', name: 'Nissan' }],
    ['niu', { filename: 'niu', name: 'NIU' }],
    ['opel', { filename: 'opel', name: 'Opel' }],
    ['orca', { filename: 'default', name: 'ORCA' }],
    ['pegassi', { filename: 'default', name: 'PEGASSI' }],
    ['peugeot', { filename: 'peugeot', name: 'Peugeot' }],
    ['piaggio', { filename: 'piaggio', name: 'Piaggio' }],
    ['plymouth', { filename: 'plymouth', name: 'Plymouth' }],
    ['polaris', { filename: 'polaris', name: 'POLARIS' }],
    ['pontiac', { filename: 'pontiac', name: 'Pontiac' }],
    ['porsche', { filename: 'porsche', name: 'Porsche' }],
    ['puma-alfa', { filename: 'puma-alfa', name: 'PUMA-ALFA' }],
    ['ram', { filename: 'ram', name: 'Ram' }],
    ['regal raptor', { filename: 'regal-raptor', name: 'REGAL RAPTOR' }],
    ['rely', { filename: 'rely', name: 'RELY' }],
    ['renault', { filename: 'renault', name: 'Renault' }],
    ['riguete', { filename: 'default', name: 'RIGUETE' }],
    ['rolls', { filename: 'rolls-royce', name: 'Rolls-Royce' }],
    ['rover', { filename: 'rover', name: 'Rover' }],
    ['royal enfield', { filename: 'royal-enfield', name: 'Royal Enfield' }],
    ['saab', { filename: 'saab', name: 'SAAB' }],
    ['sanyang', { filename: 'default', name: 'SANYANG' }],
    ['saturn', { filename: 'saturn', name: 'Saturn' }],
    ['scania', { filename: 'scania', name: 'Scania' }],
    ['seat', { filename: 'seat', name: 'SEAT' }],
    ['seres', { filename: 'seres', name: 'SERES' }],
    ['shacman', { filename: 'shacman', name: 'SHACMAN' }],
    ['shineray', { filename: 'shineray', name: 'Shineray' }],
    ['siamoto', { filename: 'default', name: 'SIAMOTO' }],
    ['sinotruk', { filename: 'sinotruk', name: 'SINOTRUK' }],
    ['smart', { filename: 'smart', name: 'Smart' }],
    ['ssangyong', { filename: 'ssangyong', name: 'Ssangyong' }],
    ['subaru', { filename: 'subaru', name: 'Subaru' }],
    ['sundown', { filename: 'sundown', name: 'Sundown' }],
    ['super soco', { filename: 'super-soco', name: 'SUPER SOCO' }],
    ['suzuki', { filename: 'suzuki', name: 'Suzuki' }],
    ['tac', { filename: 'default', name: 'TAC' }],
    ['targos', { filename: 'default', name: 'TARGOS' }],
    ['tata', { filename: 'tata', name: 'Tata' }],
    ['tesla', { filename: 'tesla', name: 'Tesla' }],
    ['tiger', { filename: 'default', name: 'TIGER' }],
    ['toyota', { filename: 'toyota', name: 'Toyota' }],
    ['traxx', { filename: 'traxx', name: 'TRAXX' }],
    ['triumph', { filename: 'triumph', name: 'Triumph' }],
    ['troller', { filename: 'troller', name: 'Troller' }],
    ['ventane motors', { filename: 'ventane-motors', name: 'Ventane Motors' }],
    ['vento', { filename: 'vento', name: 'VENTO' }],
    ['vespa', { filename: 'vespa', name: 'Vespa' }],
    ['volkswagen', { filename: 'volkswagen', name: 'Volkswagen' }],
    ['voltz', { filename: 'voltz', name: 'VOLTZ' }],
    ['volvo', { filename: 'volvo', name: 'Volvo' }],
    ['vw', { filename: 'volkswagen', name: 'Volkswagen' }],
    ['wake', { filename: 'default', name: 'Wake' }],
    ['walk', { filename: 'default', name: 'Walk' }],
    ['walkbus', { filename: 'walkbus', name: 'WALKBUS' }],
    ['watts', { filename: 'default', name: 'WATTS' }],
    ['wuyang', { filename: 'default', name: 'WUYANG' }],
    ['yamaha', { filename: 'yamaha', name: 'Yamaha' }],
    ['zontes', { filename: 'default', name: 'ZONTES' }],
    ["l'aquila", { filename: 'default', name: "L'AQUILA" }],
  ];

  static fallbackImage: string = 'https://onc-midia.s3.amazonaws.com/brands/default.webp';

  async getImageForModelCode(_brandCode: string): Promise<ModelImage> {
    return { realImagesUrl: [] };
  }

  async getImageForBrandName(
    brandName: string,
    options?: { readonly fallbackNotFoundToDefaultImage?: boolean },
  ): Promise<BrandImage> {
    if (typeof brandName !== 'string') return { mainImageUrl: StaticVehicleImageService.fallbackImage };

    const brandNameLow: string = brandName.toLowerCase();
    const result: readonly [string, StaticBrandImage] | undefined = StaticVehicleImageService.brandImages.find(
      ([brand]: readonly [string, StaticBrandImage]) => brandNameLow.startsWith(brand),
    );
    return {
      mainImageUrl: result
        ? `https://onc-midia.s3.amazonaws.com/brands/${result[1].filename}.webp`
        : options?.fallbackNotFoundToDefaultImage
        ? StaticVehicleImageService.fallbackImage
        : null,
    };
  }
}
