import { AccessoryVo } from 'src/domain/value-object/accessory.vo';
import { AggregateLocatorVo } from 'src/domain/value-object/aggregate-locator.vo';
import { AggregateVo } from 'src/domain/value-object/aggregate.vo';
import { AuctionScoreVo, AuctionVo } from 'src/domain/value-object/auction.vo';
import { AverageCostVo } from 'src/domain/value-object/average-cost.vo';
import { BasicPackVo } from 'src/domain/value-object/basic-pack.vo';
import { BasicVehicleVo } from 'src/domain/value-object/basic-vechicle.vo';
import { ComparativeAndOwnerOpinionVo } from 'src/domain/value-object/comparative-and-owner-opinion.vo';
import { ComparativeVo } from 'src/domain/value-object/comparative.vo';
import { DatasheetVo } from 'src/domain/value-object/datasheet.vo';
import { DebtsAndFinesVo } from 'src/domain/value-object/debts-and-fines.vo';
import { SignOfAccidentVo } from 'src/domain/value-object/evidence-of-theft.vo';
import { FipeDataVo, FipePriceHistoryVo } from 'src/domain/value-object/fipe-data.vo';
import { GravameVo } from 'src/domain/value-object/gravame.vo';
import { InsuranceQuotesVo } from 'src/domain/value-object/insurance-quotes.vo';
import { KmBaseVo } from 'src/domain/value-object/km-history.vo';
import { NationalBaseVo } from 'src/domain/value-object/national-base.vo';
import { OwnerHistoryVo } from 'src/domain/value-object/owner-history.vo';
import { OwnerOpinionVo } from 'src/domain/value-object/owner-opinion.vo';
import { PartnerInformationsVo } from 'src/domain/value-object/partner-informations.vo';
import { RecallVo } from 'src/domain/value-object/recall.vo';
import { RenajudVo } from 'src/domain/value-object/renajud.vo';
import { RevisionVo } from 'src/domain/value-object/revision.vo';
import { RobberyAndTheftVo } from 'src/domain/value-object/robbery-and-theft.vo';
import { StateBaseVo } from 'src/domain/value-object/state-base.vo';
import { TechnicalAdviceVo } from 'src/domain/value-object/technical-advice.vo';
import { VehicleDiagnosticVo } from 'src/domain/value-object/vehicle-diagnostic.vo';
import { VehicleReviewVo } from 'src/domain/value-object/vehicle-review.vo';
import { ModelDataVo } from '../value-object/model-data.vo';

export class VehicleEntity {
  id?: string;
  plate: string;
  chassis: string;
  engine?: string;
  renavam?: string;
  aggregate?: AggregateVo;
  stateBase?: StateBaseVo;
  nationalBase?: NationalBaseVo;
  partnerInformations?: PartnerInformationsVo;
  ownerOpinion?: OwnerOpinionVo;
  insuranceQuotes?: ReadonlyArray<InsuranceQuotesVo>;
  datasheet?: ReadonlyArray<DatasheetVo>;
  fipeData?: ReadonlyArray<FipeDataVo>;
  fipeHistory?: ReadonlyArray<FipePriceHistoryVo>;
  technicalAdvice?: TechnicalAdviceVo;
  basicPack?: ReadonlyArray<BasicPackVo>;
  basicVehicle?: BasicVehicleVo;
  debtsAndFines?: DebtsAndFinesVo;
  kmBase?: KmBaseVo;
  signOfAccident?: SignOfAccidentVo;
  vehicleDiagnostic?: VehicleDiagnosticVo;
  auction?: ReadonlyArray<AuctionVo>;
  auctionScore?: AuctionScoreVo;
  ownerHistory?: OwnerHistoryVo;
  accessories?: ReadonlyArray<AccessoryVo>;
  revision?: ReadonlyArray<RevisionVo>;
  robberyAndTheft?: RobberyAndTheftVo;
  comparative?: ReadonlyArray<ComparativeVo>;
  comparativeAndOwnerOpinion?: ComparativeAndOwnerOpinionVo;
  gravame?: ReadonlyArray<GravameVo>;
  recall?: RecallVo;
  aggregateLocator?: ReadonlyArray<AggregateLocatorVo>;
  renajud: ReadonlyArray<RenajudVo>;
  review?: VehicleReviewVo;
  averageCost?: AverageCostVo;
  model?: ModelDataVo;
}
